import { z } from 'zod';

/** ULID (Crockford base32, 26 chars). Generated by the host/client edge, never inside `shared`. */
export const Id = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/, 'expected a ULID');
export type Id = z.infer<typeof Id>;

export const LayerId = z.enum(['map', 'props', 'tokens', 'dm', 'effects']);
export type LayerId = z.infer<typeof LayerId>;
